### GET request with a header
GET http://localhost:8000
Accept: text/html

###
GET https://api.kinopoisk.dev//v1.4/movie/274730
X-API-KEY: FCE2VJ9-C2K4Z3C-MVJGV8V-XEGG0AW

###
GET https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4541869.jpg

###
GET http://127.0.0.1:8000/movies

###
POST http://127.0.0.1:8000/movies/add
Content-Type: application/json

{
  "kp_id": 35614
}

###
DELETE http://localhost:8000/movies/remove
Content-Type: application/json

{
  "kp_id": 5524
}

###
POST http://localhost:8000/movies/rate
Content-Type: application/json

{
  "film": 837525,
  "user": 5,
  "rating": 7
}

###
POST http://localhost:8000/test_postcard
Content-Type: application/json

{
  "meeting_date": "2024-11-21",
  "movies": [341, 337, 352]
}

###
PATCH http://localhost:8000/test_postcard
Content-Type: application/json

{
  "id": 1,
  "meeting_date": "2024-11-21",
  "movies": [341]
}

###
DELETE http://localhost:8000/test_postcard
Content-Type: application/json

{
  "id": 1
}

###
GET http://localhost:8000/movies/test_serializer_hell
