# Generated by Django 5.1.2 on 2024-10-14 11:43

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('watch_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('countries', models.JSONField()),
                ('budget', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('premiere', models.DateTimeField()),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('slogan', models.TextField()),
                ('duration', models.IntegerField()),
                ('poster', models.URLField()),
                ('rating_kp', models.DecimalField(decimal_places=3, max_digits=4)),
                ('rating_imdb', models.DecimalField(decimal_places=3, max_digits=4)),
                ('votes_kp', models.IntegerField()),
                ('votes_imdb', models.IntegerField()),
                ('watch_date', models.DateTimeField()),
                ('actors', models.ManyToManyField(to='lists.actor')),
                ('directors', models.ManyToManyField(to='lists.director')),
                ('genres', models.ManyToManyField(to='lists.genre')),
                ('writers', models.ManyToManyField(to='lists.writer')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.appuser')),
            ],
        ),
    ]
